Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,9 +1,10 @@
-name: Devops SonarQube Analysis
+name: CI/CD Pipeline with SonarQube & Docker Security Scan
  
 on:
   push:
-    branches:
-      - main
+    branches: [ master]
+  pull_request:
+    branches: [ master ]
  
 jobs:
   sonar:
@@ -15,11 +16,24 @@ jobs:
       - name: Run SonarScanner
         run: |
           docker run --rm -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli \
-            -Dsonar.projectKey=python \
+            -Dsonar.projectKey=test \
             -Dsonar.sources=. \
             -Dsonar.host.url=http://13.232.4.242:9092 \
             -Dsonar.login=sqp_547b8e507eb3f98c5075dacbc1e7845781bd3b19
-
+ 
+      - name: SonarQube Quality Gate Check
+        id: sonar_quality_gate
+        run: |
+          STATUS=$(curl -s -u sqp_da2630ee730f9dd8aa73e48d3ba35b4f3b57caf5: \
+          "http://13.232.4.242:9000/api/qualitygates/project_status?projectKey=test" \
+          | jq -r '.projectStatus.status')
+ 
+          echo "Quality Gate Status: $STATUS"
+          if [[ "$STATUS" != "OK" ]]; then
+            echo "❌ SonarQube Quality Gate failed!"
+            exit 1
+          fi
+ 
   docker:
     needs: sonar
     runs-on: ubuntu-latest
@@ -27,11 +41,37 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
  
-      - name: Log in to Docker Hub
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+      - name: Set Image Tag
+        run: |
+          COMMIT_HASH=$(git rev-parse --short HEAD)
+          TIMESTAMP=$(date +%Y%m%d%H%M%S)
+          echo "IMAGE_TAG=${COMMIT_HASH}_${TIMESTAMP}" >> $GITHUB_ENV
  
       - name: Build Docker Image
-        run: docker build -t samritichopra1909/sam_flask:v1 .
+        run: |
+          IMAGE_NAME=arunvel1988/devops-ci-demo-2026:${IMAGE_TAG}
+          echo "Building Docker image with tag $IMAGE_NAME"
+          docker build . --file Dockerfile --tag $IMAGE_NAME
+          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
  
-      - name: Push Docker Image to Docker Hub
-        run: docker push samritichopra1909/sam_flask:v1
+      - name: Scan Docker Image for Vulnerabilities
+        id: trivy_scan
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: "${{ env.IMAGE_NAME }}"
+          format: "table"
+          exit-code: 1 # Fails pipeline if vulnerabilities are found
+          ignore-unfixed: true
+ 
+      - name: Log in to Docker Hub
+        if: success() # Runs only if Trivy scan passed
+        run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin
+ 
+      - name: Push Docker Image
+        if: success()
+        run: |
+          docker push ${{ env.IMAGE_NAME }}
+          echo "✅ Docker image pushed: ${{ env.IMAGE_NAME }}"
+
+
+
